add keycloak sign in
5xRuby/daikichi pull request #347
Opened 2020-08-12 08:50 UTC by msf2e15032

新增 keycloak 登入

2020-08-13 05:13 UTC, elct9620 requested changes

2020-08-13 05:13 UTC, elct9620 commented on config/routes.rb
> +    as :user do
這段看起來沒有必要？

2020-08-13 05:13 UTC, elct9620 commented on config/routes.rb
> +  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
放到 Scope 外面的原因是？

2020-08-13 05:32 UTC, msf2e15032 commented on config/routes.rb
> +    as :user do
因為 sign_in 改從 keycloak 登入，所以把 sessions#new 拿掉。

2020-08-13 05:33 UTC, msf2e15032 commented on config/routes.rb
> +  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
devise 的 omniauth_callbacks，不能放在 scope 裡。

2020-08-13 05:42 UTC, elct9620 requested changes

2020-08-13 05:42 UTC, elct9620 commented on config/routes.rb
> +    as :user do
你直接關掉 `sessions` 功能，然後直接用 OmniAuth 的登入機制去處理就可以了

2020-08-13 05:42 UTC, elct9620 commented on config/routes.rb
> +  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
正常來說不會有兩個 `devise_for` 才對，因為這樣是長兩次重複的 Router

2020-08-14 04:11 UTC, elct9620 requested changes

2020-08-14 04:11 UTC, elct9620 commented on config/routes.rb
> +    delete "user/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
這邊為什麼要多做這個？用 Devise 自動生成的登出不就可以了？

2020-08-14 04:13 UTC, msf2e15032 commented on config/routes.rb
> +    delete "user/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
那個要有設定 :database_authenticatable 才會自動生出來。

2020-08-18 09:13 UTC, merged